export enum AuditActionType {
    ORDER_CREATE = "ORDER_CREATE",
    ORDER_UPDATE = "ORDER_UPDATE",
    ORDER_DELETE = "ORDER_DELETE",
    ORDER_STATUS_CHANGE = "ORDER_STATUS_CHANGE",
    ORDER_CANCEL = "ORDER_CANCEL",

    PAYMENT_CREATE = "PAYMENT_CREATE",
    PAYMENT_UPDATE = "PAYMENT_UPDATE",
    PAYMENT_DELETE = "PAYMENT_DELETE",
    PAYMENT_REFUND = "PAYMENT_REFUND",
    PAYMENT_ADJUST = "PAYMENT_ADJUST",

    ITEM_ADD = "ITEM_ADD",
    ITEM_UPDATE = "ITEM_UPDATE",
    ITEM_DELETE = "ITEM_DELETE",

    QUEUE_ADD = "QUEUE_ADD",
    QUEUE_UPDATE = "QUEUE_UPDATE",
    QUEUE_REMOVE = "QUEUE_REMOVE",
    QUEUE_REORDER = "QUEUE_REORDER",

    PRODUCT_CREATE = "PRODUCT_CREATE",
    PRODUCT_UPDATE = "PRODUCT_UPDATE",
    PRODUCT_DELETE = "PRODUCT_DELETE",

    CATEGORY_CREATE = "CATEGORY_CREATE",
    CATEGORY_UPDATE = "CATEGORY_UPDATE",
    CATEGORY_DELETE = "CATEGORY_DELETE",

    DISCOUNT_CREATE = "DISCOUNT_CREATE",
    DISCOUNT_UPDATE = "DISCOUNT_UPDATE",
    DISCOUNT_DELETE = "DISCOUNT_DELETE",
    DISCOUNT_APPLY = "DISCOUNT_APPLY",

    DELIVERY_CREATE = "DELIVERY_CREATE",
    DELIVERY_UPDATE = "DELIVERY_UPDATE",
    DELIVERY_DELETE = "DELIVERY_DELETE",

    TABLE_CREATE = "TABLE_CREATE",
    TABLE_UPDATE = "TABLE_UPDATE",
    TABLE_DELETE = "TABLE_DELETE",

    PAYMENT_METHOD_CREATE = "PAYMENT_METHOD_CREATE",
    PAYMENT_METHOD_UPDATE = "PAYMENT_METHOD_UPDATE",
    PAYMENT_METHOD_DELETE = "PAYMENT_METHOD_DELETE",

    PRODUCTS_UNIT_CREATE = "PRODUCTS_UNIT_CREATE",
    PRODUCTS_UNIT_UPDATE = "PRODUCTS_UNIT_UPDATE",
    PRODUCTS_UNIT_DELETE = "PRODUCTS_UNIT_DELETE",

    PAYMENT_ACCOUNT_CREATE = "PAYMENT_ACCOUNT_CREATE",
    PAYMENT_ACCOUNT_UPDATE = "PAYMENT_ACCOUNT_UPDATE",
    PAYMENT_ACCOUNT_ACTIVATE = "PAYMENT_ACCOUNT_ACTIVATE",
    PAYMENT_ACCOUNT_DELETE = "PAYMENT_ACCOUNT_DELETE",

    SHOP_PROFILE_UPDATE = "SHOP_PROFILE_UPDATE",

    USER_CREATE = "USER_CREATE",
    USER_UPDATE = "USER_UPDATE",
    USER_DELETE = "USER_DELETE",

    ROLE_CREATE = "ROLE_CREATE",
    ROLE_UPDATE = "ROLE_UPDATE",
    ROLE_DELETE = "ROLE_DELETE",

    BRANCH_CREATE = "BRANCH_CREATE",
    BRANCH_UPDATE = "BRANCH_UPDATE",
    BRANCH_DELETE = "BRANCH_DELETE",

    STOCK_INGREDIENT_CREATE = "STOCK_INGREDIENT_CREATE",
    STOCK_INGREDIENT_UPDATE = "STOCK_INGREDIENT_UPDATE",
    STOCK_INGREDIENT_DELETE = "STOCK_INGREDIENT_DELETE",
    STOCK_INGREDIENT_UNIT_CREATE = "STOCK_INGREDIENT_UNIT_CREATE",
    STOCK_INGREDIENT_UNIT_UPDATE = "STOCK_INGREDIENT_UNIT_UPDATE",
    STOCK_INGREDIENT_UNIT_DELETE = "STOCK_INGREDIENT_UNIT_DELETE",
    STOCK_ORDER_CREATE = "STOCK_ORDER_CREATE",
    STOCK_ORDER_UPDATE = "STOCK_ORDER_UPDATE",
    STOCK_ORDER_DELETE = "STOCK_ORDER_DELETE",
    STOCK_ORDER_CONFIRM_PURCHASE = "STOCK_ORDER_CONFIRM_PURCHASE",
    STOCK_ORDER_STATUS_UPDATE = "STOCK_ORDER_STATUS_UPDATE",

    SHIFT_OPEN = "SHIFT_OPEN",
    SHIFT_CLOSE = "SHIFT_CLOSE",
    SHIFT_CLOSE_PREVIEW = "SHIFT_CLOSE_PREVIEW",
}

export interface AuditLog {
    id: string;
    action_type: AuditActionType;
    user_id?: string | null;
    username?: string | null;
    ip_address: string;
    user_agent?: string | null;
    entity_type?: string | null;
    entity_id?: string | null;
    branch_id?: string | null;
    old_values?: Record<string, unknown> | null;
    new_values?: Record<string, unknown> | null;
    description?: string | null;
    path?: string | null;
    method?: string | null;
    created_at: Date;
}

export interface PaginatedAuditLogs {
    data: AuditLog[];
    total: number;
    page: number;
    totalPages: number;
}
